linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - goimports
    - misspell
    - goconst
    - golint
    - errcheck
    - gosec
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode
    - scopelint


issues:
  exclude:
    - "func name will be used as test\\.test.* by other packages, and that stutters; consider calling this"
    - "and that stutters; consider calling this"
    - "potential file inclusion via variable"
    - "should have( a package)? comment"
    - "error return value of `logging.setloglevel` is not checked"
    - "comment on exported"
    - "(func|method) \\w+ should be \\w+"
    - "(type|var|struct field|(method|func) parameter) `\\w+` should be `\\w+`"
    - "(g306|g301|g307|g108|g302|g204|g104)"
    - "don't use all_caps in go names"
    - "string .* has .* occurrences, make it a constant"
    - "a blank import should be only in a main or test package, or have a comment justifying it"
    - "package comment should be of the form"

  exclude-use-default: false
  exclude-rules:
    - path: lens/util/.*
      linters:
        - golint

    - path: storage/migrations/.*
      linters:
        - misspell

linters-settings:
  goconst:
    min-occurrences: 6
