version: '3.5'

services:
  notifier:
    image: filecoin/lily:v0.13.0
    env_file:
      # Check envvars for configurable options
      - ./build/lily/notifier.env
    ports:
      - 1234:1234
    volumes:
      # holds lily datastore repo
      - lily_notifier_data:/var/lib/lily
      # persist params through restarts
      - lily_notifier_tmp:/var/tmp/filecoin-proof-parameters
      # notifier-specific config
      - ./build/lily/notifier_config.toml:/var/lib/lily/config.toml
      - ./build/lily/docker_init.sh:/usr/bin/docker_init.sh
    entrypoint: /usr/bin/docker_init.sh
    command:
      - "daemon --bootstrap=false"

  grafana-agent:
    image: "grafana/agent:${GRAFANA_AGENT_VERSION}"
    network_mode: host
    restart: always
    pid: "host"
    cap_add:
      - SYS_TIME
    volumes:
      - /:/host/root:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /proc:/host/proc:ro,rslave
      - /var/run:/host/var/run:ro,rslave
      - /var/grafana-agent:/var/grafana-agent
    command:
      - "-enable-features=remote-configs"
      - "-config.file=https://raw.githubusercontent.com/filecoin-project/filcryo/main/grafana-agent/config.yaml"
      - "-config.expand-env"
    environment:
      PROMETHEUS_URL: "https://prometheus-us-central1.grafana.net/api/prom/push"
      PROMETHEUS_USERNAME: "${PROMETHEUS_USERNAME}"
      PROMETHEUS_PASSWORD: "${PROMETHEUS_PASSWORD}"
      LOKI_URL: "https://logs-prod-us-central1.grafana.net/loki/api/v1/push"
      LOKI_USERNAME: "${LOKI_USERNAME}"
      LOKI_PASSWORD: "${LOKI_PASSWORD}"
      

volumes:
  timescaledb: {}
  prometheus_data: {}
  grafana_data: {}
  lily_notifier_data: {}
  lily_worker_data: {}
  lily_notifier_tmp: {}
  lily_worker_tmp: {}
