version: '3.5'

services:
  notifier:
    image: filecoin/lily:v0.13.0
    env_file:
      # Check envvars for configurable options
      - ./build/lily/new_notifier.env
    ports:
      - 1234:1234
    volumes:
      # holds lily datastore repo
      - lily_notifier_data:/var/lib/lily
      # persist params through restarts
      - lily_notifier_tmp:/var/tmp/filecoin-proof-parameters
      # snapshot
      - ./build/lily/snapshot:/var/lib/lily/snapshot
      # notifier-specific config
      - ./build/lily/new_notifier_config.toml:/var/lib/lily/config.toml
      - ./build/lily/docker_init.sh:/usr/bin/docker_init.sh
    entrypoint: /usr/bin/docker_init.sh
    networks:
      - back-tier
    command:
      - "daemon --repo=/var/lib/lily --config=/var/lib/lily/config.toml --bootstrap=false"
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./build/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always
      

volumes:
  prometheus_data: {}
  lily_notifier_data: {}
  lily_notifier_tmp: {}
