// Code generated by: `make actors-gen`. DO NOT EDIT.
package init

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/filecoin-project/go-state-types/cbor"
	"github.com/ipfs/go-cid"

	lotusactors "github.com/filecoin-project/lotus/chain/actors"
	"github.com/filecoin-project/lotus/chain/actors/adt"
	"github.com/filecoin-project/lotus/chain/types"
	"github.com/filecoin-project/lotus/node/modules/dtypes"

	builtin0 "github.com/filecoin-project/specs-actors/actors/builtin"

	builtin2 "github.com/filecoin-project/specs-actors/v2/actors/builtin"

	builtin3 "github.com/filecoin-project/specs-actors/v3/actors/builtin"

	builtin4 "github.com/filecoin-project/specs-actors/v4/actors/builtin"

	builtin5 "github.com/filecoin-project/specs-actors/v5/actors/builtin"

	builtin6 "github.com/filecoin-project/specs-actors/v6/actors/builtin"

	builtin7 "github.com/filecoin-project/specs-actors/v7/actors/builtin"

	builtin11 "github.com/filecoin-project/go-state-types/builtin"

	"github.com/filecoin-project/lily/chain/actors"
)

var (
	Address = builtin11.InitActorAddr
	Methods = builtin11.MethodsInit
)

func Load(store adt.Store, act *types.Actor) (State, error) {
	if name, av, ok := lotusactors.GetActorMetaByCode(act.Code); ok {
		if name != actors.InitKey {
			return nil, fmt.Errorf("actor code is not init: %s", name)
		}

		switch actors.Version(av) {

		case actors.Version8:
			return load8(store, act.Head)

		case actors.Version9:
			return load9(store, act.Head)

		case actors.Version10:
			return load10(store, act.Head)

		case actors.Version11:
			return load11(store, act.Head)

		}
	}

	switch act.Code {

	case builtin0.InitActorCodeID:
		return load0(store, act.Head)

	case builtin2.InitActorCodeID:
		return load2(store, act.Head)

	case builtin3.InitActorCodeID:
		return load3(store, act.Head)

	case builtin4.InitActorCodeID:
		return load4(store, act.Head)

	case builtin5.InitActorCodeID:
		return load5(store, act.Head)

	case builtin6.InitActorCodeID:
		return load6(store, act.Head)

	case builtin7.InitActorCodeID:
		return load7(store, act.Head)

	}

	return nil, fmt.Errorf("unknown actor code %s", act.Code)
}

func MakeState(store adt.Store, av actors.Version, networkName string) (State, error) {
	switch av {

	case actors.Version0:
		return make0(store, networkName)

	case actors.Version2:
		return make2(store, networkName)

	case actors.Version3:
		return make3(store, networkName)

	case actors.Version4:
		return make4(store, networkName)

	case actors.Version5:
		return make5(store, networkName)

	case actors.Version6:
		return make6(store, networkName)

	case actors.Version7:
		return make7(store, networkName)

	case actors.Version8:
		return make8(store, networkName)

	case actors.Version9:
		return make9(store, networkName)

	case actors.Version10:
		return make10(store, networkName)

	case actors.Version11:
		return make11(store, networkName)

	}
	return nil, fmt.Errorf("unknown actor version %d", av)
}

type State interface {
	cbor.Marshaler

	Code() cid.Cid
	ActorKey() string
	ActorVersion() actors.Version

	ResolveAddress(address address.Address) (address.Address, bool, error)
	MapAddressToNewID(address address.Address) (address.Address, error)
	NetworkName() (dtypes.NetworkName, error)

	ForEachActor(func(id abi.ActorID, address address.Address) error) error

	// Remove exists to support tooling that manipulates state for testing.
	// It should not be used in production code, as init actor entries are
	// immutable.
	Remove(addrs ...address.Address) error

	// Sets the network's name. This should only be used on upgrade/fork.
	SetNetworkName(name string) error

	// Sets the next ID for the init actor. This should only be used for testing.
	SetNextID(id abi.ActorID) error

	// Sets the address map for the init actor. This should only be used for testing.
	SetAddressMap(mcid cid.Cid) error

	AddressMap() (adt.Map, error)
	AddressMapBitWidth() int
	AddressMapHashFunction() func(input []byte) []byte

	GetState() interface{}
}

func AllCodes() []cid.Cid {
	return []cid.Cid{
		(&state0{}).Code(),
		(&state2{}).Code(),
		(&state3{}).Code(),
		(&state4{}).Code(),
		(&state5{}).Code(),
		(&state6{}).Code(),
		(&state7{}).Code(),
		(&state8{}).Code(),
		(&state9{}).Code(),
		(&state10{}).Code(),
		(&state11{}).Code(),
	}
}

func VersionCodes() map[actors.Version]cid.Cid {
	return map[actors.Version]cid.Cid{
		actors.Version0:  (&state0{}).Code(),
		actors.Version2:  (&state2{}).Code(),
		actors.Version3:  (&state3{}).Code(),
		actors.Version4:  (&state4{}).Code(),
		actors.Version5:  (&state5{}).Code(),
		actors.Version6:  (&state6{}).Code(),
		actors.Version7:  (&state7{}).Code(),
		actors.Version8:  (&state8{}).Code(),
		actors.Version9:  (&state9{}).Code(),
		actors.Version10: (&state10{}).Code(),
		actors.Version11: (&state11{}).Code(),
	}
}
