// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package cbor

import (
	"fmt"
	"io"
	"math"
	"sort"

	types "github.com/filecoin-project/lotus/chain/types"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *ActorIPLDContainer) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{168}); err != nil {
		return err
	}

	// t.CurrentTipSet (types.TipSet) (struct)
	if len("current") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"current\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("current"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("current")); err != nil {
		return err
	}

	if err := t.CurrentTipSet.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ExecutedTipSet (types.TipSet) (struct)
	if len("executed") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"executed\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("executed"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("executed")); err != nil {
		return err
	}

	if err := t.ExecutedTipSet.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.MinerActors (cid.Cid) (struct)
	if len("miners") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"miners\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("miners"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("miners")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.MinerActors); err != nil {
		return xerrors.Errorf("failed to write cid field t.MinerActors: %w", err)
	}

	// t.VerifregActor (cid.Cid) (struct)
	if len("verifreg") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"verifreg\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("verifreg"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("verifreg")); err != nil {
		return err
	}

	if t.VerifregActor == nil {
		if _, err := cw.Write(cbg.CborNull); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteCid(cw, *t.VerifregActor); err != nil {
			return xerrors.Errorf("failed to write cid field t.VerifregActor: %w", err)
		}
	}

	// t.ActorStates (cid.Cid) (struct)
	if len("actors") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"actors\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("actors"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("actors")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.ActorStates); err != nil {
		return xerrors.Errorf("failed to write cid field t.ActorStates: %w", err)
	}

	// t.InitActor (cid.Cid) (struct)
	if len("init") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"init\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("init"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("init")); err != nil {
		return err
	}

	if t.InitActor == nil {
		if _, err := cw.Write(cbg.CborNull); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteCid(cw, *t.InitActor); err != nil {
			return xerrors.Errorf("failed to write cid field t.InitActor: %w", err)
		}
	}

	// t.MarketActor (cid.Cid) (struct)
	if len("market") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"market\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("market"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("market")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.MarketActor); err != nil {
		return xerrors.Errorf("failed to write cid field t.MarketActor: %w", err)
	}

	// t.PowerActor (cid.Cid) (struct)
	if len("power") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"power\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("power"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("power")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.PowerActor); err != nil {
		return xerrors.Errorf("failed to write cid field t.PowerActor: %w", err)
	}

	return nil
}

func (t *ActorIPLDContainer) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ActorIPLDContainer{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ActorIPLDContainer: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.CurrentTipSet (types.TipSet) (struct)
		case "current":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.CurrentTipSet = new(types.TipSet)
					if err := t.CurrentTipSet.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.CurrentTipSet pointer: %w", err)
					}
				}

			}
			// t.ExecutedTipSet (types.TipSet) (struct)
		case "executed":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.ExecutedTipSet = new(types.TipSet)
					if err := t.ExecutedTipSet.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.ExecutedTipSet pointer: %w", err)
					}
				}

			}
			// t.MinerActors (cid.Cid) (struct)
		case "miners":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.MinerActors: %w", err)
				}

				t.MinerActors = c

			}
			// t.VerifregActor (cid.Cid) (struct)
		case "verifreg":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					c, err := cbg.ReadCid(cr)
					if err != nil {
						return xerrors.Errorf("failed to read cid field t.VerifregActor: %w", err)
					}

					t.VerifregActor = &c
				}

			}
			// t.ActorStates (cid.Cid) (struct)
		case "actors":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.ActorStates: %w", err)
				}

				t.ActorStates = c

			}
			// t.InitActor (cid.Cid) (struct)
		case "init":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					c, err := cbg.ReadCid(cr)
					if err != nil {
						return xerrors.Errorf("failed to read cid field t.InitActor: %w", err)
					}

					t.InitActor = &c
				}

			}
			// t.MarketActor (cid.Cid) (struct)
		case "market":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.MarketActor: %w", err)
				}

				t.MarketActor = c

			}
			// t.PowerActor (cid.Cid) (struct)
		case "power":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.PowerActor: %w", err)
				}

				t.PowerActor = c

			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
