// Code generated by: `make actors-gen`. DO NOT EDIT.
package verifreg

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/ipfs/go-cid"

	"github.com/filecoin-project/lily/chain/actors/adt"

	sha256simd "github.com/minio/sha256-simd"

	verifreg0 "github.com/filecoin-project/specs-actors/actors/builtin/verifreg"
	adt0 "github.com/filecoin-project/specs-actors/actors/util/adt"

	verifreg9 "github.com/filecoin-project/go-state-types/builtin/v9/verifreg"

	actorstypes "github.com/filecoin-project/go-state-types/actors"
	"github.com/filecoin-project/go-state-types/manifest"
	"github.com/filecoin-project/lotus/chain/actors"
)

var _ State = (*state0)(nil)

func load0(store adt.Store, root cid.Cid) (State, error) {
	out := state0{store: store}
	err := store.Get(store.Context(), root, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type state0 struct {
	verifreg0.State
	store adt.Store
}

func (s *state0) ActorKey() string {
	return manifest.VerifregKey
}

func (s *state0) ActorVersion() actorstypes.Version {
	return actorstypes.Version0
}

func (s *state0) Code() cid.Cid {
	code, ok := actors.GetActorCodeID(s.ActorVersion(), s.ActorKey())
	if !ok {
		panic(fmt.Errorf("didn't find actor %v code id for actor version %d", s.ActorKey(), s.ActorVersion()))
	}

	return code
}

func (s *state0) VerifiedClientsMapBitWidth() int {

	return 5

}

func (s *state0) VerifiedClientsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256simd.Sum256(input)
		return res[:]
	}

}

func (s *state0) VerifiedClientsMap() (adt.Map, error) {

	return adt0.AsMap(s.store, s.VerifiedClients)

}

func (s *state0) VerifiersMap() (adt.Map, error) {
	return adt0.AsMap(s.store, s.Verifiers)
}

func (s *state0) VerifiersMapBitWidth() int {

	return 5

}

func (s *state0) VerifiersMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256simd.Sum256(input)
		return res[:]
	}

}

func (s *state0) RootKey() (address.Address, error) {
	return s.State.RootKey, nil
}

func (s *state0) VerifiedClientDataCap(addr address.Address) (bool, abi.StoragePower, error) {

	return getDataCap(s.store, actorstypes.Version0, s.VerifiedClientsMap, addr)

}

func (s *state0) VerifierDataCap(addr address.Address) (bool, abi.StoragePower, error) {
	return getDataCap(s.store, actorstypes.Version0, s.VerifiersMap, addr)
}

func (s *state0) RemoveDataCapProposalID(verifier address.Address, client address.Address) (bool, uint64, error) {
	return getRemoveDataCapProposalID(s.store, actorstypes.Version0, s.removeDataCapProposalIDs, verifier, client)
}

func (s *state0) ForEachVerifier(cb func(addr address.Address, dcap abi.StoragePower) error) error {
	return forEachCap(s.store, actorstypes.Version0, s.VerifiersMap, cb)
}

func (s *state0) ForEachClient(cb func(addr address.Address, dcap abi.StoragePower) error) error {

	return forEachCap(s.store, actorstypes.Version0, s.VerifiedClientsMap, cb)

}

func (s *state0) removeDataCapProposalIDs() (adt.Map, error) {
	return nil, nil

}

func (s *state0) GetState() interface{} {
	return &s.State
}

func (s *state0) GetAllocation(clientIdAddr address.Address, allocationId verifreg9.AllocationId) (*Allocation, bool, error) {

	return nil, false, fmt.Errorf("unsupported in actors v0")

}

func (s *state0) GetAllocations(clientIdAddr address.Address) (map[AllocationId]Allocation, error) {

	return nil, fmt.Errorf("unsupported in actors v0")

}

func (s *state0) GetClaim(providerIdAddr address.Address, claimId verifreg9.ClaimId) (*Claim, bool, error) {

	return nil, false, fmt.Errorf("unsupported in actors v0")

}

func (s *state0) GetClaims(providerIdAddr address.Address) (map[ClaimId]Claim, error) {

	return nil, fmt.Errorf("unsupported in actors v0")

}

func (s *state0) ClaimsMap() (adt.Map, error) {

	return nil, fmt.Errorf("unsupported in actors v0")

}

// TODO this could return an error since not all versions have a claims map
func (s *state0) ClaimsMapBitWidth() int {

	return 5

}

// TODO this could return an error since not all versions have a claims map
func (s *state0) ClaimsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256simd.Sum256(input)
		return res[:]
	}

}

func (s *state0) ClaimMapForProvider(providerIdAddr address.Address) (adt.Map, error) {

	return nil, fmt.Errorf("unsupported in actors v0")

}

func (s *state0) getInnerHamtCid(store adt.Store, key abi.Keyer, mapCid cid.Cid, bitwidth int) (cid.Cid, error) {

	return cid.Undef, fmt.Errorf("unsupported in actors v0")

}
