// Code generated by: `make actors-gen`. DO NOT EDIT.
package verifreg

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/ipfs/go-cid"

	"github.com/filecoin-project/lily/chain/actors/adt"

	"crypto/sha256"

	builtin13 "github.com/filecoin-project/go-state-types/builtin"
	adt13 "github.com/filecoin-project/go-state-types/builtin/v13/util/adt"
	verifreg13 "github.com/filecoin-project/go-state-types/builtin/v13/verifreg"

	"github.com/filecoin-project/go-state-types/big"

	verifreg9 "github.com/filecoin-project/go-state-types/builtin/v9/verifreg"

	"github.com/filecoin-project/lily/chain/actors"
)

var _ State = (*state13)(nil)

func load13(store adt.Store, root cid.Cid) (State, error) {
	out := state13{store: store}
	err := store.Get(store.Context(), root, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type state13 struct {
	verifreg13.State
	store adt.Store
}

func (s *state13) ActorKey() string {
	return actors.VerifregKey
}

func (s *state13) ActorVersion() actors.Version {
	return actors.Version13
}

func (s *state13) Code() cid.Cid {
	code, ok := actors.GetActorCodeID(s.ActorVersion(), s.ActorKey())
	if !ok {
		panic(fmt.Errorf("didn't find actor %v code id for actor version %d", s.ActorKey(), s.ActorVersion()))
	}

	return code
}

func (s *state13) VerifiedClientsMapBitWidth() int {

	return builtin13.DefaultHamtBitwidth

}

func (s *state13) VerifiedClientsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state13) VerifiedClientsMap() (adt.Map, error) {

	return nil, fmt.Errorf("unsupported in actors v13")

}

func (s *state13) VerifiersMap() (adt.Map, error) {
	return adt13.AsMap(s.store, s.Verifiers, builtin13.DefaultHamtBitwidth)
}

func (s *state13) VerifiersMapBitWidth() int {

	return builtin13.DefaultHamtBitwidth

}

func (s *state13) VerifiersMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state13) RootKey() (address.Address, error) {
	return s.State.RootKey, nil
}

func (s *state13) VerifiedClientDataCap(addr address.Address) (bool, abi.StoragePower, error) {

	return false, big.Zero(), fmt.Errorf("unsupported in actors v13")

}

func (s *state13) VerifierDataCap(addr address.Address) (bool, abi.StoragePower, error) {
	return getDataCap(s.store, actors.Version13, s.VerifiersMap, addr)
}

func (s *state13) RemoveDataCapProposalID(verifier address.Address, client address.Address) (bool, uint64, error) {
	return getRemoveDataCapProposalID(s.store, actors.Version13, s.removeDataCapProposalIDs, verifier, client)
}

func (s *state13) ForEachVerifier(cb func(addr address.Address, dcap abi.StoragePower) error) error {
	return forEachCap(s.store, actors.Version13, s.VerifiersMap, cb)
}

func (s *state13) ForEachClient(cb func(addr address.Address, dcap abi.StoragePower) error) error {

	return fmt.Errorf("unsupported in actors v13")

}

func (s *state13) removeDataCapProposalIDs() (adt.Map, error) {
	return adt13.AsMap(s.store, s.RemoveDataCapProposalIDs, builtin13.DefaultHamtBitwidth)
}

func (s *state13) GetState() interface{} {
	return &s.State
}

func (s *state13) GetAllocation(clientIdAddr address.Address, allocationId verifreg9.AllocationId) (*Allocation, bool, error) {

	alloc, ok, err := s.FindAllocation(s.store, clientIdAddr, verifreg13.AllocationId(allocationId))
	return (*Allocation)(alloc), ok, err
}

func (s *state13) GetAllocations(clientIdAddr address.Address) (map[AllocationId]Allocation, error) {

	v13Map, err := s.LoadAllocationsToMap(s.store, clientIdAddr)

	retMap := make(map[AllocationId]Allocation, len(v13Map))
	for k, v := range v13Map {
		retMap[AllocationId(k)] = Allocation(v)
	}

	return retMap, err

}

func (s *state13) GetClaim(providerIdAddr address.Address, claimId verifreg9.ClaimId) (*Claim, bool, error) {

	claim, ok, err := s.FindClaim(s.store, providerIdAddr, verifreg13.ClaimId(claimId))
	return (*Claim)(claim), ok, err

}

func (s *state13) GetClaims(providerIdAddr address.Address) (map[ClaimId]Claim, error) {

	v13Map, err := s.LoadClaimsToMap(s.store, providerIdAddr)

	retMap := make(map[ClaimId]Claim, len(v13Map))
	for k, v := range v13Map {
		retMap[ClaimId(k)] = Claim(v)
	}

	return retMap, err

}
