// Code generated by: `make actors-gen`. DO NOT EDIT.
package verifreg

import (
	"crypto/sha256"
	"fmt"

	"github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	actorstypes "github.com/filecoin-project/go-state-types/actors"
	"github.com/filecoin-project/go-state-types/big"
	builtin14 "github.com/filecoin-project/go-state-types/builtin"
	adt14 "github.com/filecoin-project/go-state-types/builtin/v14/util/adt"
	verifreg14 "github.com/filecoin-project/go-state-types/builtin/v14/verifreg"
	verifreg9 "github.com/filecoin-project/go-state-types/builtin/v9/verifreg"
	"github.com/filecoin-project/go-state-types/manifest"
	"github.com/filecoin-project/lily/chain/actors/adt"

	"github.com/filecoin-project/lotus/chain/actors"
)

var _ State = (*state14)(nil)

func load14(store adt.Store, root cid.Cid) (State, error) {
	out := state14{store: store}
	err := store.Get(store.Context(), root, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type state14 struct {
	verifreg14.State
	store adt.Store
}

func (s *state14) ActorKey() string {
	return manifest.VerifregKey
}

func (s *state14) ActorVersion() actorstypes.Version {
	return actorstypes.Version14
}

func (s *state14) Code() cid.Cid {
	code, ok := actors.GetActorCodeID(s.ActorVersion(), s.ActorKey())
	if !ok {
		panic(fmt.Errorf("didn't find actor %v code id for actor version %d", s.ActorKey(), s.ActorVersion()))
	}

	return code
}

func (s *state14) VerifiedClientsMapBitWidth() int {

	return builtin14.DefaultHamtBitwidth

}

func (s *state14) VerifiedClientsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state14) VerifiedClientsMap() (adt.Map, error) {

	return nil, fmt.Errorf("unsupported in actors v14")

}

func (s *state14) VerifiersMap() (adt.Map, error) {
	return adt14.AsMap(s.store, s.Verifiers, builtin14.DefaultHamtBitwidth)
}

func (s *state14) VerifiersMapBitWidth() int {

	return builtin14.DefaultHamtBitwidth

}

func (s *state14) VerifiersMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state14) RootKey() (address.Address, error) {
	return s.State.RootKey, nil
}

func (s *state14) VerifiedClientDataCap(addr address.Address) (bool, abi.StoragePower, error) {

	return false, big.Zero(), fmt.Errorf("unsupported in actors v14")

}

func (s *state14) VerifierDataCap(addr address.Address) (bool, abi.StoragePower, error) {
	return getDataCap(s.store, actorstypes.Version14, s.VerifiersMap, addr)
}

func (s *state14) RemoveDataCapProposalID(verifier address.Address, client address.Address) (bool, uint64, error) {
	return getRemoveDataCapProposalID(s.store, actorstypes.Version14, s.removeDataCapProposalIDs, verifier, client)
}

func (s *state14) ForEachVerifier(cb func(addr address.Address, dcap abi.StoragePower) error) error {
	return forEachCap(s.store, actorstypes.Version14, s.VerifiersMap, cb)
}

func (s *state14) ForEachClient(cb func(addr address.Address, dcap abi.StoragePower) error) error {

	return fmt.Errorf("unsupported in actors v14")

}

func (s *state14) removeDataCapProposalIDs() (adt.Map, error) {
	return adt14.AsMap(s.store, s.RemoveDataCapProposalIDs, builtin14.DefaultHamtBitwidth)
}

func (s *state14) GetState() interface{} {
	return &s.State
}

func (s *state14) GetAllocation(clientIdAddr address.Address, allocationId verifreg9.AllocationId) (*Allocation, bool, error) {

	alloc, ok, err := s.FindAllocation(s.store, clientIdAddr, verifreg14.AllocationId(allocationId))
	return (*Allocation)(alloc), ok, err
}

func (s *state14) GetAllocations(clientIdAddr address.Address) (map[AllocationId]Allocation, error) {

	v14Map, err := s.LoadAllocationsToMap(s.store, clientIdAddr)

	retMap := make(map[AllocationId]Allocation, len(v14Map))
	for k, v := range v14Map {
		retMap[AllocationId(k)] = Allocation(v)
	}

	return retMap, err

}

func (s *state14) GetClaim(providerIdAddr address.Address, claimId verifreg9.ClaimId) (*Claim, bool, error) {

	claim, ok, err := s.FindClaim(s.store, providerIdAddr, verifreg14.ClaimId(claimId))
	return (*Claim)(claim), ok, err

}

func (s *state14) GetClaims(providerIdAddr address.Address) (map[ClaimId]Claim, error) {

	v14Map, err := s.LoadClaimsToMap(s.store, providerIdAddr)

	retMap := make(map[ClaimId]Claim, len(v14Map))
	for k, v := range v14Map {
		retMap[ClaimId(k)] = Claim(v)
	}

	return retMap, err

}

func (s *state14) ClaimsMap() (adt.Map, error) {

	return adt14.AsMap(s.store, s.Claims, builtin14.DefaultHamtBitwidth)

}

// TODO this could return an error since not all versions have a claims map
func (s *state14) ClaimsMapBitWidth() int {

	return builtin14.DefaultHamtBitwidth

}

// TODO this could return an error since not all versions have a claims map
func (s *state14) ClaimsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state14) ClaimMapForProvider(providerIdAddr address.Address) (adt.Map, error) {

	innerHamtCid, err := s.getInnerHamtCid(s.store, abi.IdAddrKey(providerIdAddr), s.Claims, builtin14.DefaultHamtBitwidth)
	if err != nil {
		return nil, err
	}
	return adt14.AsMap(s.store, innerHamtCid, builtin14.DefaultHamtBitwidth)

}

func (s *state14) getInnerHamtCid(store adt.Store, key abi.Keyer, mapCid cid.Cid, bitwidth int) (cid.Cid, error) {

	actorToHamtMap, err := adt14.AsMap(store, mapCid, bitwidth)
	if err != nil {
		return cid.Undef, fmt.Errorf("couldn't get outer map: %x", err)
	}

	var innerHamtCid cbg.CborCid
	if found, err := actorToHamtMap.Get(key, &innerHamtCid); err != nil {
		return cid.Undef, fmt.Errorf("looking up key: %s: %w", key, err)
	} else if !found {
		return cid.Undef, fmt.Errorf("did not find key: %s", key)
	}

	return cid.Cid(innerHamtCid), nil

}
