// Code generated by: `make actors-gen`. DO NOT EDIT.
package verifreg

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/ipfs/go-cid"

	"github.com/filecoin-project/lily/chain/actors/adt"

	"crypto/sha256"

	builtin3 "github.com/filecoin-project/specs-actors/v3/actors/builtin"

	verifreg3 "github.com/filecoin-project/specs-actors/v3/actors/builtin/verifreg"
	adt3 "github.com/filecoin-project/specs-actors/v3/actors/util/adt"

	verifreg9 "github.com/filecoin-project/go-state-types/builtin/v9/verifreg"

	actorstypes "github.com/filecoin-project/go-state-types/actors"
	"github.com/filecoin-project/go-state-types/manifest"
	"github.com/filecoin-project/lotus/chain/actors"
)

var _ State = (*state3)(nil)

func load3(store adt.Store, root cid.Cid) (State, error) {
	out := state3{store: store}
	err := store.Get(store.Context(), root, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type state3 struct {
	verifreg3.State
	store adt.Store
}

func (s *state3) ActorKey() string {
	return manifest.VerifregKey
}

func (s *state3) ActorVersion() actorstypes.Version {
	return actorstypes.Version3
}

func (s *state3) Code() cid.Cid {
	code, ok := actors.GetActorCodeID(s.ActorVersion(), s.ActorKey())
	if !ok {
		panic(fmt.Errorf("didn't find actor %v code id for actor version %d", s.ActorKey(), s.ActorVersion()))
	}

	return code
}

func (s *state3) VerifiedClientsMapBitWidth() int {

	return builtin3.DefaultHamtBitwidth

}

func (s *state3) VerifiedClientsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state3) VerifiedClientsMap() (adt.Map, error) {

	return adt3.AsMap(s.store, s.VerifiedClients, builtin3.DefaultHamtBitwidth)

}

func (s *state3) VerifiersMap() (adt.Map, error) {
	return adt3.AsMap(s.store, s.Verifiers, builtin3.DefaultHamtBitwidth)
}

func (s *state3) VerifiersMapBitWidth() int {

	return builtin3.DefaultHamtBitwidth

}

func (s *state3) VerifiersMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state3) RootKey() (address.Address, error) {
	return s.State.RootKey, nil
}

func (s *state3) VerifiedClientDataCap(addr address.Address) (bool, abi.StoragePower, error) {

	return getDataCap(s.store, actorstypes.Version3, s.VerifiedClientsMap, addr)

}

func (s *state3) VerifierDataCap(addr address.Address) (bool, abi.StoragePower, error) {
	return getDataCap(s.store, actorstypes.Version3, s.VerifiersMap, addr)
}

func (s *state3) RemoveDataCapProposalID(verifier address.Address, client address.Address) (bool, uint64, error) {
	return getRemoveDataCapProposalID(s.store, actorstypes.Version3, s.removeDataCapProposalIDs, verifier, client)
}

func (s *state3) ForEachVerifier(cb func(addr address.Address, dcap abi.StoragePower) error) error {
	return forEachCap(s.store, actorstypes.Version3, s.VerifiersMap, cb)
}

func (s *state3) ForEachClient(cb func(addr address.Address, dcap abi.StoragePower) error) error {

	return forEachCap(s.store, actorstypes.Version3, s.VerifiedClientsMap, cb)

}

func (s *state3) removeDataCapProposalIDs() (adt.Map, error) {
	return nil, nil

}

func (s *state3) GetState() interface{} {
	return &s.State
}

func (s *state3) GetAllocation(clientIdAddr address.Address, allocationId verifreg9.AllocationId) (*Allocation, bool, error) {

	return nil, false, fmt.Errorf("unsupported in actors v3")

}

func (s *state3) GetAllocations(clientIdAddr address.Address) (map[AllocationId]Allocation, error) {

	return nil, fmt.Errorf("unsupported in actors v3")

}

func (s *state3) GetClaim(providerIdAddr address.Address, claimId verifreg9.ClaimId) (*Claim, bool, error) {

	return nil, false, fmt.Errorf("unsupported in actors v3")

}

func (s *state3) GetClaims(providerIdAddr address.Address) (map[ClaimId]Claim, error) {

	return nil, fmt.Errorf("unsupported in actors v3")

}

func (s *state3) ClaimsMap() (adt.Map, error) {

	return nil, fmt.Errorf("unsupported in actors v3")

}

// TODO this could return an error since not all versions have a claims map
func (s *state3) ClaimsMapBitWidth() int {

	return builtin3.DefaultHamtBitwidth

}

// TODO this could return an error since not all versions have a claims map
func (s *state3) ClaimsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state3) ClaimMapForProvider(providerIdAddr address.Address) (adt.Map, error) {

	return nil, fmt.Errorf("unsupported in actors v3")

}

func (s *state3) getInnerHamtCid(store adt.Store, key abi.Keyer, mapCid cid.Cid, bitwidth int) (cid.Cid, error) {

	return cid.Undef, fmt.Errorf("unsupported in actors v3")

}
