// Code generated by: `make actors-gen`. DO NOT EDIT.
package verifreg

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/ipfs/go-cid"

	"github.com/filecoin-project/lily/chain/actors"
	"github.com/filecoin-project/lily/chain/actors/adt"

	"crypto/sha256"

	builtin8 "github.com/filecoin-project/specs-actors/v8/actors/builtin"
	verifreg8 "github.com/filecoin-project/specs-actors/v8/actors/builtin/verifreg"
	adt8 "github.com/filecoin-project/specs-actors/v8/actors/util/adt"
)

var _ State = (*state8)(nil)

func load8(store adt.Store, root cid.Cid) (State, error) {
	out := state8{store: store}
	err := store.Get(store.Context(), root, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type state8 struct {
	verifreg8.State
	store adt.Store
}

func (s *state8) RootKey() (address.Address, error) {
	return s.State.RootKey, nil
}

func (s *state8) VerifiedClientDataCap(addr address.Address) (bool, abi.StoragePower, error) {
	return getDataCap(s.store, actors.Version8, s.VerifiedClientsMap, addr)
}

func (s *state8) VerifierDataCap(addr address.Address) (bool, abi.StoragePower, error) {
	return getDataCap(s.store, actors.Version8, s.VerifiersMap, addr)
}

func (s *state8) ForEachVerifier(cb func(addr address.Address, dcap abi.StoragePower) error) error {
	return forEachCap(s.store, actors.Version8, s.VerifiersMap, cb)
}

func (s *state8) ForEachClient(cb func(addr address.Address, dcap abi.StoragePower) error) error {
	return forEachCap(s.store, actors.Version8, s.VerifiedClientsMap, cb)
}

func (s *state8) VerifiedClientsMap() (adt.Map, error) {
	return adt8.AsMap(s.store, s.VerifiedClients, builtin8.DefaultHamtBitwidth)
}

func (s *state8) VerifiedClientsMapBitWidth() int {

	return builtin8.DefaultHamtBitwidth

}

func (s *state8) VerifiedClientsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state8) VerifiersMap() (adt.Map, error) {
	return adt8.AsMap(s.store, s.Verifiers, builtin8.DefaultHamtBitwidth)
}

func (s *state8) VerifiersMapBitWidth() int {

	return builtin8.DefaultHamtBitwidth

}

func (s *state8) VerifiersMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state8) ActorKey() string {
	return actors.VerifregKey
}

func (s *state8) ActorVersion() actors.Version {
	return actors.Version8
}

func (s *state8) Code() cid.Cid {
	code, ok := actors.GetActorCodeID(s.ActorVersion(), s.ActorKey())
	if !ok {
		panic(fmt.Errorf("didn't find actor %v code id for actor version %d", s.ActorKey(), s.ActorVersion()))
	}

	return code
}
