// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package economics

import (
	"fmt"
	"io"
	"math"
	"sort"

	abi "github.com/filecoin-project/go-state-types/abi"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufChainEconomics = []byte{141}

func (t *ChainEconomics) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufChainEconomics); err != nil {
		return err
	}

	// t.Height (abi.ChainEpoch) (int64)
	if t.Height >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Height)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Height-1)); err != nil {
			return err
		}
	}

	// t.StateRoot (cid.Cid) (struct)

	if err := cbg.WriteCid(cw, t.StateRoot); err != nil {
		return xerrors.Errorf("failed to write cid field t.StateRoot: %w", err)
	}

	// t.TotalGasLimit (int64) (int64)
	if t.TotalGasLimit >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.TotalGasLimit)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.TotalGasLimit-1)); err != nil {
			return err
		}
	}

	// t.TotalUniqueGasLimit (int64) (int64)
	if t.TotalUniqueGasLimit >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.TotalUniqueGasLimit)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.TotalUniqueGasLimit-1)); err != nil {
			return err
		}
	}

	// t.NumBlocks (int64) (int64)
	if t.NumBlocks >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.NumBlocks)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.NumBlocks-1)); err != nil {
			return err
		}
	}

	// t.ParentBaseFee (big.Int) (struct)
	if err := t.ParentBaseFee.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.BaseFee (big.Int) (struct)
	if err := t.BaseFee.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FilVested (big.Int) (struct)
	if err := t.FilVested.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FilMined (big.Int) (struct)
	if err := t.FilMined.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FilBurnt (big.Int) (struct)
	if err := t.FilBurnt.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FilLocked (big.Int) (struct)
	if err := t.FilLocked.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FilCirculating (big.Int) (struct)
	if err := t.FilCirculating.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FilReservedDisbursed (big.Int) (struct)
	if err := t.FilReservedDisbursed.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *ChainEconomics) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ChainEconomics{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 13 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Height (abi.ChainEpoch) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Height = abi.ChainEpoch(extraI)
	}
	// t.StateRoot (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(cr)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.StateRoot: %w", err)
		}

		t.StateRoot = c

	}
	// t.TotalGasLimit (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.TotalGasLimit = int64(extraI)
	}
	// t.TotalUniqueGasLimit (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.TotalUniqueGasLimit = int64(extraI)
	}
	// t.NumBlocks (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.NumBlocks = int64(extraI)
	}
	// t.ParentBaseFee (big.Int) (struct)

	{

		if err := t.ParentBaseFee.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.ParentBaseFee: %w", err)
		}

	}
	// t.BaseFee (big.Int) (struct)

	{

		if err := t.BaseFee.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.BaseFee: %w", err)
		}

	}
	// t.FilVested (big.Int) (struct)

	{

		if err := t.FilVested.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.FilVested: %w", err)
		}

	}
	// t.FilMined (big.Int) (struct)

	{

		if err := t.FilMined.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.FilMined: %w", err)
		}

	}
	// t.FilBurnt (big.Int) (struct)

	{

		if err := t.FilBurnt.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.FilBurnt: %w", err)
		}

	}
	// t.FilLocked (big.Int) (struct)

	{

		if err := t.FilLocked.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.FilLocked: %w", err)
		}

	}
	// t.FilCirculating (big.Int) (struct)

	{

		if err := t.FilCirculating.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.FilCirculating: %w", err)
		}

	}
	// t.FilReservedDisbursed (big.Int) (struct)

	{

		if err := t.FilReservedDisbursed.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.FilReservedDisbursed: %w", err)
		}

	}
	return nil
}
