// Code generated by: `make actors-gen`. DO NOT EDIT.
package power

import (
	"bytes"
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/filecoin-project/lily/chain/actors"
	"github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"

	"github.com/filecoin-project/lily/chain/actors/adt"
	"github.com/filecoin-project/lily/chain/actors/builtin"

	"crypto/sha256"

	builtin10 "github.com/filecoin-project/go-state-types/builtin"
	power10 "github.com/filecoin-project/go-state-types/builtin/v10/power"
	adt10 "github.com/filecoin-project/go-state-types/builtin/v10/util/adt"
)

var _ State = (*state10)(nil)

func load10(store adt.Store, root cid.Cid) (State, error) {
	out := state10{store: store}
	err := store.Get(store.Context(), root, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type state10 struct {
	power10.State
	store adt.Store
}

func (s *state10) TotalLocked() (abi.TokenAmount, error) {
	return s.TotalPledgeCollateral, nil
}

func (s *state10) TotalPower() (Claim, error) {
	return Claim{
		RawBytePower:    s.TotalRawBytePower,
		QualityAdjPower: s.TotalQualityAdjPower,
	}, nil
}

// Committed power to the network. Includes miners below the minimum threshold.
func (s *state10) TotalCommitted() (Claim, error) {
	return Claim{
		RawBytePower:    s.TotalBytesCommitted,
		QualityAdjPower: s.TotalQABytesCommitted,
	}, nil
}

func (s *state10) MinerPower(addr address.Address) (Claim, bool, error) {
	claims, err := s.ClaimsMap()
	if err != nil {
		return Claim{}, false, err
	}
	var claim power10.Claim
	ok, err := claims.Get(abi.AddrKey(addr), &claim)
	if err != nil {
		return Claim{}, false, err
	}
	return Claim{
		RawBytePower:    claim.RawBytePower,
		QualityAdjPower: claim.QualityAdjPower,
	}, ok, nil
}

func (s *state10) MinerNominalPowerMeetsConsensusMinimum(a address.Address) (bool, error) {
	return s.State.MinerNominalPowerMeetsConsensusMinimum(s.store, a)
}

func (s *state10) TotalPowerSmoothed() (builtin.FilterEstimate, error) {
	return builtin.FilterEstimate(s.State.ThisEpochQAPowerSmoothed), nil
}

func (s *state10) MinerCounts() (uint64, uint64, error) {
	return uint64(s.State.MinerAboveMinPowerCount), uint64(s.State.MinerCount), nil
}

func (s *state10) ListAllMiners() ([]address.Address, error) {
	claims, err := s.ClaimsMap()
	if err != nil {
		return nil, err
	}

	var miners []address.Address
	err = claims.ForEach(nil, func(k string) error {
		a, err := address.NewFromBytes([]byte(k))
		if err != nil {
			return err
		}
		miners = append(miners, a)
		return nil
	})
	if err != nil {
		return nil, err
	}

	return miners, nil
}

func (s *state10) ForEachClaim(cb func(miner address.Address, claim Claim) error) error {
	claims, err := s.ClaimsMap()
	if err != nil {
		return err
	}

	var claim power10.Claim
	return claims.ForEach(&claim, func(k string) error {
		a, err := address.NewFromBytes([]byte(k))
		if err != nil {
			return err
		}
		return cb(a, Claim{
			RawBytePower:    claim.RawBytePower,
			QualityAdjPower: claim.QualityAdjPower,
		})
	})
}

func (s *state10) ClaimsChanged(other State) (bool, error) {
	other10, ok := other.(*state10)
	if !ok {
		// treat an upgrade as a change, always
		return true, nil
	}
	return !s.State.Claims.Equals(other10.State.Claims), nil
}

func (s *state10) ClaimsMap() (adt.Map, error) {
	return adt10.AsMap(s.store, s.Claims, builtin10.DefaultHamtBitwidth)
}

func (s *state10) ClaimsMapBitWidth() int {

	return builtin10.DefaultHamtBitwidth

}

func (s *state10) ClaimsMapHashFunction() func(input []byte) []byte {

	return func(input []byte) []byte {
		res := sha256.Sum256(input)
		return res[:]
	}

}

func (s *state10) decodeClaim(val *cbg.Deferred) (Claim, error) {
	var ci power10.Claim
	if err := ci.UnmarshalCBOR(bytes.NewReader(val.Raw)); err != nil {
		return Claim{}, err
	}
	return fromV10Claim(ci), nil
}

func fromV10Claim(v10 power10.Claim) Claim {
	return Claim{
		RawBytePower:    v10.RawBytePower,
		QualityAdjPower: v10.QualityAdjPower,
	}
}

func (s *state10) ActorKey() string {
	return actors.PowerKey
}

func (s *state10) ActorVersion() actors.Version {
	return actors.Version10
}

func (s *state10) Code() cid.Cid {
	code, ok := actors.GetActorCodeID(s.ActorVersion(), s.ActorKey())
	if !ok {
		panic(fmt.Errorf("didn't find actor %v code id for actor version %d", s.ActorKey(), s.ActorVersion()))
	}

	return code
}
