// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package actors

import (
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
